[metadata]
name = spindle-dev
version = 0.1.0
description = Indexing and searching SPD sub-matrices from spatial datasets.
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
author = sarkar_lab

[options]
package_dir =
    = src
packages = find:
install_requires =
    numpy
    scipy
    pandas
    scikit-learn
    umap-learn
    scanpy
python_requires = >=3.9

[options.packages.find]
where = src
