"""Write results/.gitignore so git tracks exactly the files the figure scripts read.

Runs every figure script (fig[1-7]_*.py, figS*_*.py) in its own process under a Python audit hook that records
each file opened under results/, then writes results/.gitignore: ignore everything, re-include the directories,
results/README.md, the .gitignore itself and every recorded file. Everything else in results/ (per-seed and
per-query outputs, caches, indexes) stays on disk only; the figures redraw from a clone.

Run it after changing what a figure reads, then `git add results` (and `git rm -r --cached` what dropped out):

  python scripts/figures/list_figure_inputs.py            # all figure scripts
  python scripts/figures/list_figure_inputs.py --dry-run  # print the list only
"""

import argparse
import os
import runpy
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESULTS = HERE.parents[1] / "results"
HEADER = """# Generated by scripts/figures/list_figure_inputs.py: git tracks only the files the figure scripts read.
# Everything else in results/ (per-seed / per-query outputs, caches, indexes) stays on disk; rerun the
# experiments to regenerate it. Regenerate this file after changing what a figure reads.
*
!*/
!.gitignore
!README.md
"""


def child(out, script):
    """Run one figure script, appending the results/ files it opens to ``out``."""
    root = os.path.realpath(RESULTS) + os.sep
    seen = set()

    def hook(event, args):
        if event == "open" and args and isinstance(args[0], (str, bytes, os.PathLike)):
            p = os.path.realpath(os.fsdecode(args[0]))
            if p.startswith(root):
                seen.add(p[len(root):])

    sys.addaudithook(hook)
    sys.argv = [script]
    sys.path.insert(0, str(HERE))
    try:
        runpy.run_path(script, run_name="__main__")
    finally:
        with open(out, "a") as fh:
            fh.writelines(f"{p}\n" for p in sorted(seen))


def main():
    if len(sys.argv) == 4 and sys.argv[1] == "--child":
        return child(sys.argv[2], sys.argv[3])
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true", help="print the files, do not write results/.gitignore")
    args = ap.parse_args()
    scripts = sorted(HERE.glob("fig[1-7]_*.py")) + sorted(HERE.glob("figS[0-9]*_*.py"))
    with tempfile.NamedTemporaryFile("r", suffix=".txt") as tmp:
        for s in scripts:
            r = subprocess.run([sys.executable, __file__, "--child", tmp.name, s.name], cwd=HERE,
                               stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)
            if r.returncode:
                sys.exit(f"{s.name} failed; fix it before listing inputs:\n{r.stderr[-2000:]}")
            print(f"ran {s.name}", flush=True)
        files = sorted({ln.strip() for ln in open(tmp.name) if ln.strip()})
    files = [f for f in files if (RESULTS / f).is_file()]
    size = sum((RESULTS / f).stat().st_size for f in files)
    print(f"{len(files)} figure inputs, {size / 1e6:.1f} MB")
    if args.dry_run:
        print("\n".join(files))
        return
    (RESULTS / ".gitignore").write_text(HEADER + "".join(f"!/{f}\n" for f in files))
    print(f"wrote {RESULTS / '.gitignore'}")


if __name__ == "__main__":
    main()
