import os
import sys
from datetime import datetime

# -- Path setup --------------------------------------------------------------
sys.path.insert(0, os.path.abspath('../src'))

# -- Project information -----------------------------------------------------
project = 'Spindle'
author = 'sarkar_lab'
copyright = f"{datetime.now().year}, {author}"

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'myst_parser',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 2,
}
html_static_path = ['_static']

# Copy arbitrary files from repo/docs/examples into the built HTML root
# so example HTML files generated by `scripts/build_notebooks.py` appear
# at /examples/... in the published site.
html_extra_path = ['../docs/examples']

# MyST (Markdown) settings
myst_enable_extensions = [
    'deflist',
    'html_admonition',
    'html_image',
]
