#!/usr/bin/env python3
"""
organize_panel_data.py
======================
Curates the raw benchmark CSV outputs into clean, panel-specific CSVs stored in
``results/panel_data/``.

Run this script once after running benchmarks to refresh the panel data.
The figure-generation script (generate_result_figure.py) then reads exclusively from
``results/panel_data/``, so you can tweak or hand-edit any panel CSV without
re-running expensive benchmarks.

Usage
-----
    python scripts/organize_panel_data.py

Output
------
    results/panel_data/
        panel_A.csv
        panel_B.csv
        panel_C.csv                    -- partial-query efficiency (dist_gap & speedup)
        panel_D.csv                    -- Recall@1 by dataset
        panel_E.csv                    -- partial-query robustness
        panel_F_xenium_coords.csv      -- Xenium cells (x, y)
        panel_G_visium_coords.csv      -- Visium spots (x, y)
        panel_F_G_tile_boxes.csv
        panel_H_recall_metrics.csv
        panel_I_spatial_cells.csv
        panel_I_top_matches.csv
        panel_J_pathway_scores.csv
"""

from pathlib import Path
import pandas as pd

# -- Project root (scripts/ -> parent) ----------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
RAW_ROOT     = PROJECT_ROOT / 'results'
OUT_DIR      = RAW_ROOT / 'panel_data'
OUT_DIR.mkdir(parents=True, exist_ok=True)


# -- Helper: write CSV with a commented header block --------------------------
def write_csv_with_header(df: pd.DataFrame, out_path: Path, header_lines: list):
    """
    Write *df* to *out_path* as a standard CSV, preceded by comment lines
    (each prefixed with '#') that describe the dataset, columns, and provenance.
    """
    with out_path.open('w') as fh:
        for line in header_lines:
            fh.write(f'# {line}\n')
        fh.write('#\n')
        df.to_csv(fh, index=False)
    print(f'  OK  {out_path.relative_to(PROJECT_ROOT)}  ({len(df)} rows)')


# -- Helper: canonical human-readable dataset names ---------------------------
_SPECIAL_NAMES = {
    'lymph_node_5k': 'Lymph Node (5k)',
    'kidney_nondiseased': 'Kidney (Non-diseased)',
}


def clean_dataset_name(raw: str) -> str:
    """
    Convert an internal dataset key (e.g. "xenium_human_lymph_node_5k") into a
    clean, human-readable label with no underscores and no "Xenium"/"Human"
    wording (e.g. "Lymph Node (5k)").
    """
    key = raw.strip()
    for prefix in ('xenium_human_', 'xenium_'):
        if key.lower().startswith(prefix):
            key = key[len(prefix):]
            break

    if key.lower() in _SPECIAL_NAMES:
        return _SPECIAL_NAMES[key.lower()]

    return key.replace('_', ' ').title()


# -----------------------------------------------------------------------------
# Panel A  -- Index scalability (build time & index size per dataset)
# Source   : results/holdout_validation/index_scalability_summary.csv
# Generated: benchmarks/index_datasets.py
# -----------------------------------------------------------------------------
def curate_panel_a():
    src = RAW_ROOT / 'holdout_validation' / 'index_scalability_summary.csv'
    if not src.exists():
        print(f'  SKIP Panel A -- source not found: {src}')
        return

    df = pd.read_csv(src)
    rename = {}
    for col in df.columns:
        cl = col.lower()
        if 'build' in cl and 'time' in cl:
            rename[col] = 'build_time_s'
        elif 'index' in cl and 'size' in cl:
            rename[col] = 'index_size_mb'
        elif 'cell' in cl:
            rename[col] = 'num_cells'
        elif 'dataset' in cl:
            rename[col] = 'dataset_key'
    df = df.rename(columns=rename)

    df['dataset'] = df['dataset_key'].apply(clean_dataset_name)
    df = df.sort_values('num_cells').reset_index(drop=True)
    df = df[['dataset', 'dataset_key', 'num_cells', 'build_time_s', 'index_size_mb']]

    header = [
        'Panel A -- Index Scalability',
        '',
        'Dual-axis bar chart: SPINDLE index build time (left axis) and index size on',
        'disk (right axis) for each dataset, sorted by ascending cell count.',
        '',
        'Columns:',
        '  dataset        -- Human-readable dataset name (e.g. "Breast Cancer")',
        '  dataset_key    -- Internal dataset key (matches benchmark output)',
        '  num_cells      -- Number of cells in the dataset',
        '  build_time_s   -- Wall-clock time to build the SPINDLE index (seconds)',
        '  index_size_mb  -- Disk footprint of the saved SPINDLE index (megabytes)',
        '',
        'Source CSV : results/holdout_validation/index_scalability_summary.csv',
        'Generated by: benchmarks/index_datasets.py',
    ]
    write_csv_with_header(df, OUT_DIR / 'panel_A.csv', header)


# -----------------------------------------------------------------------------
# Panel B  -- Query acceleration / speedup per dataset
# Source   : results/holdout_validation/benchmark_summary.csv
# Generated: benchmarks/holdout_validation.py
# -----------------------------------------------------------------------------
def curate_panel_b():
    src = RAW_ROOT / 'holdout_validation' / 'benchmark_summary.csv'
    if not src.exists():
        print(f'  SKIP Panel B -- source not found: {src}')
        return

    df = pd.read_csv(src)

    keep = ['Dataset', 'mean_speedup', 'mean_spindle_time_ms', 'mean_brute_force_time_ms',
            'recall_at_1', 'overlap_at_5', 'overlap_at_10', 'overlap_at_20']
    available = [c for c in keep if c in df.columns]
    out = df[available].copy()
    out = out.rename(columns={'Dataset': 'dataset_key'})
    out['dataset'] = out['dataset_key'].apply(clean_dataset_name)
    if 'mean_speedup' in out.columns:
        out = out.sort_values('mean_speedup', ascending=True).reset_index(drop=True)

    header = [
        'Panel B -- Query Acceleration (Speedup vs. Brute-Force Search)',
        '',
        'Horizontal bar chart: per-dataset speedup of SPINDLE ANN search over exact',
        'brute-force search (higher = faster). Sorted ascending so fastest dataset',
        'appears at the top of the horizontal bar chart.',
        '',
        'Columns:',
        '  dataset_key             -- Internal dataset key (matches benchmark output)',
        '  dataset                 -- Human-readable label used as the axis tick',
        '  mean_speedup            -- Mean wall-clock speedup across holdout queries (x)',
        '  mean_spindle_time_ms    -- Mean SPINDLE query wall-clock time (ms)',
        '  mean_brute_force_time_ms-- Mean exact brute-force query wall-clock time (ms)',
        '  recall_at_1             -- Fraction of queries where top-1 result is exact (0-1)',
        '  overlap_at_5            -- Mean Jaccard overlap of top-5 with brute-force (0-1)',
        '  overlap_at_10           -- Mean Jaccard overlap of top-10 with brute-force (0-1)',
        '  overlap_at_20           -- Mean Jaccard overlap of top-20 with brute-force (0-1)',
        '',
        'Source CSV : results/holdout_validation/benchmark_summary.csv',
        'Generated by: benchmarks/holdout_validation.py',
    ]
    write_csv_with_header(out, OUT_DIR / 'panel_B.csv', header)


# -----------------------------------------------------------------------------
# Panel C  -- Partial-query efficiency: distance gap & speedup by gene-count bin
# Source   : results/partial_panel_search/overall_benchmark_metrics.csv
# Generated: benchmarks/partial_panel_search.py
# -----------------------------------------------------------------------------
def curate_panel_c():
    src = RAW_ROOT / 'partial_panel_search' / 'overall_benchmark_metrics.csv'
    if not src.exists():
        print(f'  SKIP Panel C -- source not found: {src}')
        return

    df = pd.read_csv(src)
    if 'Length_Bin' not in df.columns:
        print(f'  WARNING Panel C: "Length_Bin" column not found in {list(df.columns)}')
        return

    bin_order = ['<=6 genes', '7-12 genes', '13-16 genes', '>16 genes']
    grp = df.groupby('Length_Bin').agg(
        mean_dist_gap=('dist_gap', 'mean'),
        mean_speedup=('speedup', 'mean'),
        mean_spindle_time_ms=('spindle_time_ms', 'mean'),
        mean_brute_force_time_ms=('brute_force_time_ms', 'mean'),
        n_queries=('speedup', 'size'),
    ).reset_index()
    grp = grp.rename(columns={'Length_Bin': 'length_bin'})
    grp['sort_key'] = grp['length_bin'].map({v: i for i, v in enumerate(bin_order)}).fillna(99)
    out = grp.sort_values('sort_key').drop(columns='sort_key').reset_index(drop=True)

    header = [
        'Panel C -- Partial-Query Efficiency: Distance Gap & Speedup vs. Gene Panel Length',
        '',
        'Dual-axis chart: mean distance gap from the true exact-match (lower = more',
        'accurate) and mean speedup over brute-force search, as a function of how many',
        'genes the query panel contains. Companion to Panel E (which shows Recall@1 /',
        'Overlap@10 for the same gene-count bins) -- this panel shows two different,',
        'previously-unplotted metrics (dist_gap, speedup) rather than repeating Panel E.',
        '',
        'Columns:',
        '  length_bin                -- Gene-count bin (<=6 / 7-12 / 13-16 / >16 genes)',
        '  mean_dist_gap              -- Mean distance from SPINDLE top-1 to the true',
        '                                 exact-match distance (lower is better)',
        '  mean_speedup               -- Mean wall-clock speedup vs. brute-force (x)',
        '  mean_spindle_time_ms       -- Mean SPINDLE query time (ms)',
        '  mean_brute_force_time_ms   -- Mean brute-force query time (ms)',
        '  n_queries                  -- Number of query instances averaged in this bin',
        '',
        'Source CSV : results/partial_panel_search/overall_benchmark_metrics.csv',
        'Generated by: benchmarks/partial_panel_search.py',
    ]
    write_csv_with_header(out, OUT_DIR / 'panel_C.csv', header)


# -----------------------------------------------------------------------------
# Panel D  -- Recall@1 by dataset (bar chart)
# Source   : results/holdout_validation/benchmark_summary.csv
# Generated: benchmarks/holdout_validation.py
# -----------------------------------------------------------------------------
def curate_panel_d():
    src = RAW_ROOT / 'holdout_validation' / 'benchmark_summary.csv'
    if not src.exists():
        print(f'  SKIP Panel D -- source not found: {src}')
        return

    df = pd.read_csv(src)
    keep = ['Dataset', 'recall_at_1', 'overlap_at_5', 'overlap_at_10', 'overlap_at_20',
            'overlap_at_30', 'overlap_at_50', 'mean_speedup', 'mean_spindle_time_ms',
            'mean_brute_force_time_ms']
    available = [c for c in keep if c in df.columns]
    out = df[available].copy()
    out = out.rename(columns={'Dataset': 'dataset_key'})
    out['dataset'] = out['dataset_key'].apply(clean_dataset_name)
    out = out.sort_values('recall_at_1', ascending=True).reset_index(drop=True)

    header = [
        'Panel D -- Retrieval Accuracy by Dataset (Recall@1)',
        '',
        'Bar chart: fraction of holdout queries where the SPINDLE top-1 result is',
        'exactly the true nearest neighbour, shown per dataset. Companion to Panel C',
        '(aggregate cumulative curve) -- shows consistency across tissue types.',
        '',
        'Columns:',
        '  dataset_key              -- Internal dataset key',
        '  dataset                  -- Human-readable label used on the chart axis',
        '  recall_at_1              -- Fraction of queries with exact top-1 match (0-1)',
        '  overlap_at_5/10/20/30/50 -- Mean Jaccard overlap with brute-force at K (0-1)',
        '  mean_speedup             -- Mean wall-clock speedup vs. brute-force (x)',
        '  mean_spindle_time_ms     -- Mean SPINDLE query time (ms)',
        '  mean_brute_force_time_ms -- Mean brute-force query time (ms)',
        '',
        'Source CSV : results/holdout_validation/benchmark_summary.csv',
        'Generated by: benchmarks/holdout_validation.py',
    ]
    write_csv_with_header(out, OUT_DIR / 'panel_D.csv', header)


# -----------------------------------------------------------------------------
# Panel E  -- Partial-panel search: metrics binned by query gene-count
# Source   : results/partial_panel_search/overall_benchmark_metrics.csv
# Generated: benchmarks/partial_panel_search.py
# -----------------------------------------------------------------------------
def curate_panel_e():
    src = RAW_ROOT / 'partial_panel_search' / 'overall_benchmark_metrics.csv'
    if not src.exists():
        print(f'  SKIP Panel E -- source not found: {src}')
        return

    df = pd.read_csv(src)

    bin_order = ['<=6 genes', '7-12 genes', '13-16 genes', '>16 genes']

    if 'Length_Bin' not in df.columns:
        print(f'  WARNING Panel E: "Length_Bin" column not found in {list(df.columns)}')
        return

    col_r = next((c for c in ['recall_at_1', 'hit_top_1', 'recall@1'] if c in df.columns), None)
    col_o = next((c for c in ['overlap_at_10', 'overlap_10', 'overlap@10'] if c in df.columns), None)
    if col_r is None or col_o is None:
        print(f'  WARNING Panel E: could not find recall/overlap columns in {list(df.columns)}')
        return

    grp = df.groupby('Length_Bin').agg(
        recall_at_1_pct=(col_r, 'mean'),
        overlap_at_10_pct=(col_o, 'mean'),
        n_queries=(col_r, 'size'),
    ).reset_index()
    grp = grp.rename(columns={'Length_Bin': 'length_bin'})
    for col in ['recall_at_1_pct', 'overlap_at_10_pct']:
        if grp[col].max() <= 1.0:
            grp[col] *= 100
    grp['sort_key'] = grp['length_bin'].map({v: i for i, v in enumerate(bin_order)}).fillna(99)
    out = grp.sort_values('sort_key').drop(columns='sort_key').reset_index(drop=True)

    header = [
        'Panel E -- Partial-Query Robustness (Metrics by Gene-Count Bin)',
        '',
        'Line chart: Recall@1 and Overlap@10 as a function of how many genes the',
        'query panel contains (partial coverage of the full spatial transcriptomics',
        'panel). Values are averaged across all datasets and query tiles per bin.',
        '',
        'Columns:',
        '  length_bin         -- Gene-count bin (<=6 / 7-12 / 13-16 / >16 genes)',
        '  recall_at_1_pct    -- Mean Recall@1 (%) -- exact match in top-1 result',
        '  overlap_at_10_pct  -- Mean Overlap@10 (%) -- Jaccard overlap with top-10',
        '  n_queries          -- Number of query instances averaged in this bin',
        '',
        'Source CSV : results/partial_panel_search/overall_benchmark_metrics.csv',
        'Generated by: benchmarks/partial_panel_search.py',
    ]
    write_csv_with_header(out, OUT_DIR / 'panel_E.csv', header)


# -----------------------------------------------------------------------------
# Panel F/G  -- Cross-modal search: Xenium & Visium coords (density-gradient
#               scatter), tile boxes, and Panel H recall metrics
# Source   : results/cross_modal_search/spatial_coords_sample.csv
#            results/cross_modal_search/tile_overlay_boxes.csv
#            results/cross_modal_search/summary.csv
# Generated: benchmarks/cross_modal_search.py
# -----------------------------------------------------------------------------
def curate_panel_f_g():
    coords_src  = RAW_ROOT / 'cross_modal_search' / 'spatial_coords_sample.csv'
    boxes_src   = RAW_ROOT / 'cross_modal_search' / 'tile_overlay_boxes.csv'
    metrics_src = RAW_ROOT / 'cross_modal_search' / 'summary.csv'

    # -- Xenium / Visium coordinates (plotted as a density gradient) -----------
    if coords_src.exists():
        df_coords = pd.read_csv(coords_src)

        xe = df_coords[df_coords['modality'] == 'Xenium'][['x', 'y']].reset_index(drop=True)
        xe_header = [
            'Panel F -- Xenium Cell Coordinates',
            '',
            'Scatter-plot layer: spatial (x, y) coordinates of a representative sample of',
            'Xenium single cells from the human breast-cancer dataset. Rendered as a',
            'density gradient (hexbin) in the figure, not colored by cell type.',
            '',
            'Columns:',
            '  x -- Spatial x-coordinate of the cell centroid (microns)',
            '  y -- Spatial y-coordinate of the cell centroid (microns)',
            '',
            'Source CSV : results/cross_modal_search/spatial_coords_sample.csv (Xenium rows)',
            'Generated by: benchmarks/cross_modal_search.py',
        ]
        write_csv_with_header(xe, OUT_DIR / 'panel_F_xenium_coords.csv', xe_header)

        vi = df_coords[df_coords['modality'] == 'Visium'][['x', 'y']].reset_index(drop=True)
        vi_header = [
            'Panel G -- Visium Spot Coordinates',
            '',
            'Scatter-plot layer: spatial (x, y) coordinates of Visium spots from the',
            'matched human breast-cancer tissue section. Rendered as a density gradient',
            '(hexbin) in the figure, not colored by cell type.',
            '',
            'Columns:',
            '  x -- Spatial x-coordinate of the Visium spot centroid',
            '  y -- Spatial y-coordinate of the Visium spot centroid',
            '',
            'Source CSV : results/cross_modal_search/spatial_coords_sample.csv (Visium rows)',
            'Generated by: benchmarks/cross_modal_search.py',
        ]
        write_csv_with_header(vi, OUT_DIR / 'panel_G_visium_coords.csv', vi_header)
    else:
        print(f'  SKIP Panel F/G coords -- source not found: {coords_src}')

    # -- Tile overlay boxes ---------------------------------------------------
    if boxes_src.exists():
        df_boxes = pd.read_csv(boxes_src)
        boxes_header = [
            'Panel F/G -- Tile Overlay Bounding Boxes',
            '',
            'Rectangle patches drawn over the cell-coordinate scatter plots to visualise',
            'the spatial tiles used for cross-modal retrieval.',
            '',
            'Columns:',
            '  modality -- "Xenium" or "Visium"',
            '  id       -- Tile index within the modality',
            '  x0, y0   -- Bottom-left corner of the bounding box',
            '  x1, y1   -- Top-right corner of the bounding box',
            '',
            'Source CSV : results/cross_modal_search/tile_overlay_boxes.csv',
            'Generated by: benchmarks/cross_modal_search.py',
        ]
        write_csv_with_header(df_boxes, OUT_DIR / 'panel_F_G_tile_boxes.csv', boxes_header)
    else:
        print(f'  SKIP Panel F/G boxes -- source not found: {boxes_src}')

    # -- Panel H: recall / overlap metrics (mean +/- s.d. across seeds) --------
    if metrics_src.exists():
        df_s = pd.read_csv(metrics_src)
        dir_map = {'x2v': 'Xenium to Visium', 'v2x': 'Visium to Xenium'}
        df_m = pd.DataFrame({
            'direction': df_s['direction'],
            'direction_label': df_s['direction'].map(dir_map).fillna(df_s['direction']),
            'n_seeds': df_s['n_seeds'],
        })
        for col in ['recall_at_eps_0.1', 'recall_at_eps_0.5', 'overlap_at_eps_0.5', 'overlap_at_eps_1.0']:
            df_m[f'{col}_pct'] = df_s[f'mean_{col}'] * 100
            df_m[f'{col}_sd_pct'] = df_s[f'sd_{col}'] * 100
        df_m['mean_speedup'] = df_s['mean_mean_speedup']
        df_m['sd_speedup'] = df_s['sd_mean_speedup']

        metrics_header = [
            'Panel H -- Cross-Modal Retrieval Metrics',
            '',
            'Bar chart of Recall@eps=0.1 and Overlap@eps=0.5 per query direction in the',
            'Xenium <-> Visium cross-modal search experiment (human breast-cancer dataset),',
            'mean +/- s.d. across seeds (all-niche search, block-diagonalized ground truth).',
            '',
            'Columns:',
            '  direction              -- Internal key ("x2v"=Xenium->Visium, "v2x"=Visium->Xenium)',
            '  direction_label        -- Human-readable label used on the chart axis',
            '  n_seeds                -- Number of seeds aggregated',
            '  <metric>_pct / _sd_pct -- Mean / s.d. across seeds (%), metric in',
            '                            recall_at_eps_{0.1,0.5}, overlap_at_eps_{0.5,1.0}',
            '  mean_speedup / sd_speedup -- Speedup vs. whole-matrix brute force',
            '',
            'Source CSV : results/cross_modal_search/summary.csv',
            'Generated by: benchmarks/cross_modal_search.py + benchmarks/multiseed_cross_modal_search.py',
        ]
        write_csv_with_header(df_m, OUT_DIR / 'panel_H_recall_metrics.csv', metrics_header)
    else:
        print(f'  SKIP Panel H metrics -- source not found: {metrics_src}')


# -----------------------------------------------------------------------------
# Panel I  -- Gene signature spatial map
# Panel J  -- Pathway score bar chart
# Source   : results/gene_signature_search/breast_cancer/Luminal_Tumor_Core_*.csv
#            results/gene_signature_search/benchmark_metrics.csv
# Generated: benchmarks/gene_signature_search.py  (run on breast_cancer dataset)
# -----------------------------------------------------------------------------
def curate_panel_i_j():
    cells_src   = (RAW_ROOT / 'gene_signature_search' / 'breast_cancer'
                   / 'Luminal_Tumor_Core_spatial_cells.csv')
    matches_src = (RAW_ROOT / 'gene_signature_search' / 'breast_cancer'
                   / 'Luminal_Tumor_Core_top_matches.csv')
    metrics_src = RAW_ROOT / 'gene_signature_search' / 'benchmark_metrics.csv'

    # -- Spatial cells --------------------------------------------------------
    if cells_src.exists():
        df_cells = pd.read_csv(cells_src)
        cells_header = [
            'Panel I -- Luminal Tumour Core: All Spatial Cells',
            '',
            'Full scatter-plot background for the gene-signature spatial discovery map.',
            'Each row is one cell from the Xenium breast-cancer dataset coloured by its',
            'Scanpy sc.score_genes() Pathway Score for the Luminal Tumor Core signature.',
            '',
            'LEFT sub-panel : all cells coloured by continuous pathway score (magma).',
            'RIGHT sub-panel: cells inside SPINDLE top-match tiles highlighted (no tile',
            '                 boundary boxes -- colour alone marks the matched region).',
            '',
            'Columns:',
            '  x             -- Spatial x-coordinate of the cell centroid (microns)',
            '  y             -- Spatial y-coordinate of the cell centroid (microns)',
            '  pathway_score -- Scanpy sc.score_genes() value; higher = stronger signature',
            '',
            'Source CSV : results/gene_signature_search/breast_cancer/',
            '             Luminal_Tumor_Core_spatial_cells.csv',
            'Generated by: benchmarks/gene_signature_search.py  (dataset: breast_cancer)',
        ]
        write_csv_with_header(df_cells, OUT_DIR / 'panel_I_spatial_cells.csv', cells_header)
    else:
        print(f'  SKIP Panel I spatial cells -- source not found: {cells_src}')

    # -- Top-match tiles (kept for provenance; no longer drawn as boxes) ------
    if matches_src.exists():
        df_matches = pd.read_csv(matches_src)
        matches_header = [
            'Panel I -- Luminal Tumour Core: SPINDLE Top-Match Tile Locations',
            '',
            'Tiles returned by SPINDLE for the Luminal Tumor Core gene-list query.',
            'Rank 1 = best match. Retained here for provenance/reproducibility even',
            'though the figure no longer draws bounding-box rectangles for these tiles.',
            '',
            'Columns:',
            '  rank    -- Retrieval rank (1 = top match)',
            '  tile_id -- Internal tile index in the spatial index',
            '  x0, y0  -- Bottom-left corner of the tile bounding box (microns)',
            '  x1, y1  -- Top-right corner of the tile bounding box (microns)',
            '',
            'Source CSV : results/gene_signature_search/breast_cancer/',
            '             Luminal_Tumor_Core_top_matches.csv',
            'Generated by: benchmarks/gene_signature_search.py  (dataset: breast_cancer)',
        ]
        write_csv_with_header(df_matches, OUT_DIR / 'panel_I_top_matches.csv', matches_header)
    else:
        print(f'  SKIP Panel I top matches -- source not found: {matches_src}')

    # -- Pathway scores (Panel J) ----------------------------------------------
    ROW_TO_LABEL = {
        'Luminal_Tumor_Core':      'Invasive Tumour\n& DCIS Core',
        'Basal_Myoepithelial':     'Myoepithelial\n& Basal Layer',
        'Proliferation_Signature': 'Proliferating\nTumour Cells',
        'Endothelial_Vascular':    'Vasculature &\nEndothelial',
        'Macrophage_Myeloid':      'Macrophage &\nDendritic Cell',
    }
    SCORE_COLS = ['background_score',
                  'enrichment_score_at_5', 'enrichment_score_at_10',
                  'enrichment_score_at_20', 'enrichment_score_at_50',
                  'enrichment_score_at_200',
                  'enrichment_lift_at_5', 'enrichment_lift_at_10',
                  'enrichment_lift_at_20', 'enrichment_lift_at_50']

    rows = []
    if metrics_src.exists():
        try:
            df_m = pd.read_csv(metrics_src, index_col=0)
            for row_key, label in ROW_TO_LABEL.items():
                if row_key in df_m.index:
                    row = {'niche_key': row_key, 'niche_label': label}
                    for col in SCORE_COLS:
                        if col in df_m.columns:
                            row[col] = float(df_m.loc[row_key, col])
                    rows.append(row)
            if not rows or max(abs(r.get('background_score', 0.0)) for r in rows) < 0.1:
                print('  WARNING Panel J: scores implausible -- skipping')
                rows = []
        except Exception as e:
            print(f'  WARNING Panel J: could not read benchmark_metrics.csv ({e})')
            rows = []

    if not rows:
        print('  SKIP Panel J pathway scores -- no usable data')
        return

    df_pw = pd.DataFrame(rows)
    scores_header = [
        'Panel J -- Pathway Score Comparison (All Five Gene-List Niches)',
        '',
        'Horizontal grouped bar chart: Tissue Background score vs. SPINDLE Top-10',
        'enrichment score for each of the five gene-signature queries on breast-cancer.',
        'Scores are Scanpy sc.score_genes() values; enrichment_lift_at_K is the percent',
        'lift of the Top-K enrichment score over the tissue background.',
        '',
        'Columns:',
        '  niche_key                -- Internal key matching the benchmark CSV index',
        '  niche_label               -- Multi-line label used on the chart y-axis',
        '  background_score          -- Mean sc.score_genes() over all tissue cells',
        '  enrichment_score_at_{K}   -- Mean sc.score_genes() inside top-K SPINDLE tiles',
        '  enrichment_lift_at_{K}    -- % lift of top-K enrichment over background',
        '',
        'Source CSV : results/gene_signature_search/benchmark_metrics.csv',
        'Generated by: benchmarks/gene_signature_search.py  (dataset: breast_cancer)',
    ]
    write_csv_with_header(df_pw, OUT_DIR / 'panel_J_pathway_scores.csv', scores_header)


# -- Entry point --------------------------------------------------------------
def main():
    print('SPINDLE -- Organising panel data ...')
    print(f'  Output directory: {OUT_DIR.relative_to(PROJECT_ROOT)}\n')

    curate_panel_a()
    curate_panel_b()
    curate_panel_c()
    curate_panel_d()
    curate_panel_e()
    curate_panel_f_g()
    curate_panel_i_j()

    print(f'\n{"="*60}')
    print('Done.  Panel CSVs are in results/panel_data/')
    print('Run scripts/generate_result_figure.py to regenerate figures.')
    print(f'{"="*60}')


if __name__ == '__main__':
    main()
