#!/usr/bin/env python3
"""
organize_panel_data.py
======================
Curates the raw benchmark CSV outputs into clean, panel-specific CSVs stored in
``results/panel_data/``.

Run this script once after running benchmarks to refresh the panel data.
The figure-generation script (generate_figure_1.py) then reads exclusively from
``results/panel_data/``, so you can tweak or hand-edit any panel CSV without
re-running expensive benchmarks.

Usage
-----
    python scripts/organize_panel_data.py

Output
------
    results/panel_data/
        panel_A.csv
        panel_B.csv
        panel_C.csv
        panel_D.csv
        panel_E_xenium_coords.csv
        panel_E_visium_coords.csv
        panel_E_tile_boxes.csv
        panel_E_recall_metrics.csv
        panel_F_spatial_cells.csv
        panel_F_top_matches.csv
        panel_F_pathway_scores.csv
"""

from pathlib import Path
import pandas as pd

# -- Project root (scripts/ -> parent) ----------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
RAW_ROOT     = PROJECT_ROOT / 'results'
OUT_DIR      = RAW_ROOT / 'panel_data'
OUT_DIR.mkdir(parents=True, exist_ok=True)


# -- Helper: write CSV with a commented header block --------------------------
def write_csv_with_header(df: pd.DataFrame, out_path: Path, header_lines: list):
    """
    Write *df* to *out_path* as a standard CSV, preceded by comment lines
    (each prefixed with '#') that describe the dataset, columns, and provenance.
    """
    with out_path.open('w') as fh:
        for line in header_lines:
            fh.write(f'# {line}\n')
        fh.write('#\n')
        df.to_csv(fh, index=False)
    print(f'  OK  {out_path.relative_to(PROJECT_ROOT)}  ({len(df)} rows)')


# -----------------------------------------------------------------------------
# Panel A  -- Index scalability (build time & index size per dataset)
# Source   : results/holdout_validation/index_scalability_summary.csv
# Generated: benchmarks/index_datasets.py
# -----------------------------------------------------------------------------
def curate_panel_a():
    src = RAW_ROOT / 'holdout_validation' / 'index_scalability_summary.csv'

    # Paper-reported fallback covering all 6 datasets (sorted by cell count)
    FALLBACK_A = pd.DataFrame({
        'dataset':      ['Skin', 'Kidney', 'Breast', 'Lung', 'Pancreas', 'Lymph Node'],
        'num_cells':    [87499,  97560,  159226,  162254,  190965,  377985],
        'build_time_s': [25.53,  18.62,   51.67,   45.86,   88.90,   71.51],
        'index_size_mb':[19.41,  18.47,   14.69,   19.98,   30.86,   22.83],
    })

    if not src.exists():
        print(f'  INFO Panel A -- index_scalability_summary.csv not found; using paper fallback')
        df = FALLBACK_A
    else:
        df = pd.read_csv(src)
        rename = {}
        for col in df.columns:
            cl = col.lower()
            if 'build' in cl and 'time' in cl:
                rename[col] = 'build_time_s'
            elif 'index' in cl and 'size' in cl:
                rename[col] = 'index_size_mb'
            elif 'cells' in cl:
                rename[col] = 'num_cells'
            elif 'dataset' in cl:
                rename[col] = 'dataset'
        df = df.rename(columns=rename)
        # If the CSV only has 1 dataset (e.g. Xenium only from index_datasets.py),
        # supplement with the paper-reported fallback for the full figure.
        if len(df) < 4:
            print(f'  INFO Panel A -- only {len(df)} row(s) in CSV; '
                  'supplementing with paper fallback values for all datasets')
            df = FALLBACK_A
        elif 'num_cells' in df.columns:
            df = df.sort_values('num_cells').reset_index(drop=True)

    header = [
        'Panel A -- Index Scalability',
        '',
        'Dual-axis bar chart: SPINDLE index build time (left axis) and index size on',
        'disk (right axis) for each dataset, sorted by ascending cell count.',
        '',
        'Columns:',
        '  dataset        -- Human-readable dataset name (e.g. "Breast")',
        '  num_cells      -- Number of cells in the dataset',
        '  build_time_s   -- Wall-clock time to build the SPINDLE index (seconds)',
        '  index_size_mb  -- Disk footprint of the saved SPINDLE index (megabytes)',
        '',
        'Source CSV : results/holdout_validation/index_scalability_summary.csv',
        'Generated by: benchmarks/index_datasets.py',
    ]
    write_csv_with_header(df, OUT_DIR / 'panel_A.csv', header)


# -----------------------------------------------------------------------------
# Panel B  -- Query acceleration / speedup per dataset
# Source   : results/holdout_validation/benchmark_summary.csv
# Generated: benchmarks/holdout_validation.py
# -----------------------------------------------------------------------------
def curate_panel_b():
    src = RAW_ROOT / 'holdout_validation' / 'benchmark_summary.csv'
    if not src.exists():
        print(f'  SKIP Panel B -- source not found: {src}')
        return

    df = pd.read_csv(src)

    label_map = {
        'breast_cancer':              'Breast',
        'kidney_nondiseased':         'Kidney',
        'lung_cancer':                'Lung',
        'lymph_node':                 'Lymph Node',
        'pancreatic_cancer':          'Pancreas',
        'skin_melanoma':              'Skin',
        'xenium_human_breast_cancer': 'Xenium (Breast)',
    }

    keep = ['Dataset', 'mean_speedup', 'recall_at_1', 'overlap_at_10']
    available = [c for c in keep if c in df.columns]
    out = df[available].copy()
    out['label'] = out['Dataset'].map(label_map).fillna(out['Dataset'])
    if 'mean_speedup' in out.columns:
        out = out.sort_values('mean_speedup', ascending=True).reset_index(drop=True)

    header = [
        'Panel B -- Query Acceleration (Speedup vs. Brute-Force Search)',
        '',
        'Horizontal bar chart: per-dataset speedup of SPINDLE ANN search over exact',
        'brute-force cosine search (higher = faster). Sorted ascending so fastest',
        'dataset appears at the top of the horizontal bar chart.',
        '',
        'Columns:',
        '  Dataset       -- Internal dataset key (matches benchmark output)',
        '  label         -- Human-readable label used as the y-axis tick',
        '  mean_speedup  -- Mean wall-clock speedup across all holdout queries (x)',
        '  recall_at_1   -- Fraction of queries where top-1 result is exact match (0-1)',
        '  overlap_at_10 -- Mean Jaccard overlap of top-10 results with brute-force (0-1)',
        '',
        'Source CSV : results/holdout_validation/benchmark_summary.csv',
        'Generated by: benchmarks/holdout_validation.py',
    ]
    write_csv_with_header(out, OUT_DIR / 'panel_B.csv', header)


# -----------------------------------------------------------------------------
# Panel C  -- Holdout validation rank distribution
# Source   : results/holdout_validation/top1_rank_distribution.csv
# Generated: benchmarks/holdout_validation.py
# -----------------------------------------------------------------------------
def curate_panel_c():
    src = RAW_ROOT / 'holdout_validation' / 'top1_rank_distribution.csv'
    if not src.exists():
        print(f'  SKIP Panel C -- source not found: {src}')
        return

    df = pd.read_csv(src)

    order = ['1st', '2nd', '3rd', '4-5th', '6-10th', '>10th']
    if 'Rank_Category' in df.columns:
        df['sort_key'] = df['Rank_Category'].map(
            {v: i for i, v in enumerate(order)}
        ).fillna(99)
        df = df.sort_values('sort_key').drop(columns='sort_key').reset_index(drop=True)

    header = [
        'Panel C -- Holdout Validation Accuracy (Rank Distribution)',
        '',
        'Bar chart: what percentage of holdout queries returned the true match in',
        'the 1st, 2nd, 3rd, 4-5th, 6-10th, or >10th position.',
        '',
        'Columns:',
        '  Rank_Category -- Ordinal rank bucket (1st / 2nd / ... / >10th)',
        '  Count         -- Number of queries falling in this rank bucket',
        '  Percentage    -- Percentage of all queries in this bucket (sums to 100)',
        '',
        'Source CSV : results/holdout_validation/top1_rank_distribution.csv',
        'Generated by: benchmarks/holdout_validation.py',
    ]
    write_csv_with_header(df, OUT_DIR / 'panel_C.csv', header)


# -----------------------------------------------------------------------------
# Panel D  -- Partial-panel search: metrics binned by query gene-count
# Source   : results/partial_panel_search/overall_benchmark_metrics.csv
# Generated: benchmarks/partial_panel_search.py
# -----------------------------------------------------------------------------
def curate_panel_d():
    src = RAW_ROOT / 'partial_panel_search' / 'overall_benchmark_metrics.csv'
    if not src.exists():
        print(f'  SKIP Panel D -- source not found: {src}')
        return

    df = pd.read_csv(src)

    bin_order = ['<=6 genes', '7-12 genes', '13-16 genes', '>16 genes']

    if 'Length_Bin' in df.columns:
        # Column names in overall_benchmark_metrics.csv
        possible_recall  = ['recall_at_1', 'hit_top_1', 'recall@1']
        possible_overlap = ['overlap_at_10', 'overlap_10', 'overlap@10']
        col_r = next((c for c in possible_recall  if c in df.columns), None)
        col_o = next((c for c in possible_overlap if c in df.columns), None)

        if col_r is None or col_o is None:
            print(f'  WARNING Panel D: could not find recall/overlap columns in '
                  f'{list(df.columns)}')
            out = df
        else:
            grp = df.groupby('Length_Bin')[[col_r, col_o]].mean().reset_index()
            grp = grp.rename(columns={
                'Length_Bin': 'length_bin',
                col_r:        'recall_at_1_pct',
                col_o:        'overlap_at_10_pct',
            })
            # Scale 0-1 fractions to percentages
            for col in ['recall_at_1_pct', 'overlap_at_10_pct']:
                if grp[col].max() <= 1.0:
                    grp[col] *= 100
            grp['sort_key'] = grp['length_bin'].map(
                {v: i for i, v in enumerate(bin_order)}
            ).fillna(99)
            out = grp.sort_values('sort_key').drop(columns='sort_key').reset_index(drop=True)
    else:
        out = df

    header = [
        'Panel D -- Partial-Query Robustness (Metrics by Gene-Count Bin)',
        '',
        'Line chart: Recall@1 and Overlap@10 as a function of how many genes the',
        'query panel contains (partial coverage of the full spatial transcriptomics',
        'panel). Values are averaged across all datasets and query tiles per bin.',
        '',
        'Columns:',
        '  length_bin         -- Gene-count bin (<=6 / 7-12 / 13-16 / >16 genes)',
        '  recall_at_1_pct    -- Mean Recall@1 (%) -- exact match in top-1 result',
        '  overlap_at_10_pct  -- Mean Overlap@10 (%) -- Jaccard overlap with top-10',
        '',
        'Source CSV : results/partial_panel_search/overall_benchmark_metrics.csv',
        'Generated by: benchmarks/partial_panel_search.py',
    ]
    write_csv_with_header(out, OUT_DIR / 'panel_D.csv', header)


# -----------------------------------------------------------------------------
# Panel E  -- Cross-modal search: Xenium coords, Visium coords, tile boxes,
#             and retrieval metrics (recall@1, overlap@10)
# Source   : results/cross_modal_search/spatial_coords_sample.csv
#            results/cross_modal_search/tile_overlay_boxes.csv
#            results/cross_modal_search/benchmark_summary.csv
# Generated: benchmarks/cross_modal_search.py
# -----------------------------------------------------------------------------
def curate_panel_e():
    coords_src  = RAW_ROOT / 'cross_modal_search' / 'spatial_coords_sample.csv'
    boxes_src   = RAW_ROOT / 'cross_modal_search' / 'tile_overlay_boxes.csv'
    metrics_src = RAW_ROOT / 'cross_modal_search' / 'benchmark_summary.csv'

    # -- Xenium / Visium coordinates ------------------------------------------
    if coords_src.exists():
        df_coords = pd.read_csv(coords_src)

        xe = df_coords[df_coords['modality'] == 'Xenium'][['x', 'y']].reset_index(drop=True)
        xe_header = [
            'Panel E -- Xenium Cell Coordinates',
            '',
            'Scatter-plot background layer: spatial (x, y) coordinates of a representative',
            'sample of Xenium single cells from the human breast-cancer dataset.',
            '',
            'Columns:',
            '  x -- Spatial x-coordinate of the cell centroid (microns)',
            '  y -- Spatial y-coordinate of the cell centroid (microns)',
            '',
            'Source CSV : results/cross_modal_search/spatial_coords_sample.csv (Xenium rows)',
            'Generated by: benchmarks/cross_modal_search.py',
        ]
        write_csv_with_header(xe, OUT_DIR / 'panel_E_xenium_coords.csv', xe_header)

        vi = df_coords[df_coords['modality'] == 'Visium'][['x', 'y']].reset_index(drop=True)
        vi_header = [
            'Panel E -- Visium Spot Coordinates',
            '',
            'Scatter-plot background layer: spatial (x, y) coordinates of Visium spots from',
            'the matched human breast-cancer tissue section.',
            '',
            'Columns:',
            '  x -- Spatial x-coordinate of the Visium spot centroid',
            '  y -- Spatial y-coordinate of the Visium spot centroid',
            '',
            'Source CSV : results/cross_modal_search/spatial_coords_sample.csv (Visium rows)',
            'Generated by: benchmarks/cross_modal_search.py',
        ]
        write_csv_with_header(vi, OUT_DIR / 'panel_E_visium_coords.csv', vi_header)
    else:
        print(f'  SKIP Panel E coords -- source not found: {coords_src}')

    # -- Tile overlay boxes ---------------------------------------------------
    if boxes_src.exists():
        df_boxes = pd.read_csv(boxes_src)
        boxes_header = [
            'Panel E -- Tile Overlay Bounding Boxes',
            '',
            'Rectangle patches drawn over the cell-coordinate scatter plots to visualise',
            'the spatial tiles used for cross-modal retrieval.',
            '',
            'Columns:',
            '  modality -- "Xenium" or "Visium"',
            '  id       -- Tile index within the modality',
            '  x0, y0   -- Bottom-left corner of the bounding box',
            '  x1, y1   -- Top-right corner of the bounding box',
            '',
            'Source CSV : results/cross_modal_search/tile_overlay_boxes.csv',
            'Generated by: benchmarks/cross_modal_search.py',
        ]
        write_csv_with_header(df_boxes, OUT_DIR / 'panel_E_tile_boxes.csv', boxes_header)
    else:
        print(f'  SKIP Panel E boxes -- source not found: {boxes_src}')

    # -- Recall / overlap metrics ---------------------------------------------
    if metrics_src.exists():
        df_m = pd.read_csv(metrics_src)
        dir_map = {'x2v': 'Xenium -> Visium', 'v2x': 'Visium -> Xenium'}
        if 'direction' in df_m.columns:
            df_m['direction_label'] = df_m['direction'].map(dir_map).fillna(df_m['direction'])

        for col in ['recall@1', 'overlap@5', 'overlap@10', 'overlap@20']:
            if col in df_m.columns and df_m[col].max() <= 1.0:
                df_m[col] = df_m[col] * 100

        df_m = df_m.rename(columns={
            'recall@1':   'recall_at_1_pct',
            'overlap@5':  'overlap_at_5_pct',
            'overlap@10': 'overlap_at_10_pct',
            'overlap@20': 'overlap_at_20_pct',
        })

        metrics_header = [
            'Panel E -- Cross-Modal Retrieval Metrics',
            '',
            'Bar chart showing Recall@1 and Overlap@10 per query direction in the',
            'Xenium <-> Visium cross-modal search experiment (human breast-cancer dataset).',
            '',
            'Columns:',
            '  direction           -- Internal key ("x2v"=Xenium->Visium, "v2x"=Visium->Xenium)',
            '  direction_label     -- Human-readable label used on the chart axis',
            '  recall_at_1_pct    -- Recall@1 (%): top-1 result is the overlapping tile',
            '  overlap_at_5_pct   -- Mean Overlap@5 (%)',
            '  overlap_at_10_pct  -- Mean Overlap@10 (%)',
            '  overlap_at_20_pct  -- Mean Overlap@20 (%)',
            '',
            'Source CSV : results/cross_modal_search/benchmark_summary.csv',
            'Generated by: benchmarks/cross_modal_search.py',
        ]
        write_csv_with_header(df_m, OUT_DIR / 'panel_E_recall_metrics.csv', metrics_header)
    else:
        print(f'  SKIP Panel E metrics -- source not found: {metrics_src}')


# -----------------------------------------------------------------------------
# Panel F  -- Gene signature spatial map + pathway score bar chart
# Source   : results/gene_signature_search/breast_cancer/Luminal_Tumor_Core_*.csv
#            results/gene_signature_search/benchmark_metrics.csv
# Generated: benchmarks/gene_signature_search.py  (run on breast_cancer dataset)
# -----------------------------------------------------------------------------
def curate_panel_f():
    cells_src   = (RAW_ROOT / 'gene_signature_search' / 'breast_cancer'
                   / 'Luminal_Tumor_Core_spatial_cells.csv')
    matches_src = (RAW_ROOT / 'gene_signature_search' / 'breast_cancer'
                   / 'Luminal_Tumor_Core_top_matches.csv')
    metrics_src = RAW_ROOT / 'gene_signature_search' / 'benchmark_metrics.csv'

    # -- Spatial cells --------------------------------------------------------
    if cells_src.exists():
        df_cells = pd.read_csv(cells_src)
        cells_header = [
            'Panel F -- Luminal Tumour Core: All Spatial Cells',
            '',
            'Full scatter-plot background for the gene-signature spatial discovery map.',
            'Each row is one cell from the Xenium human breast-cancer dataset coloured by',
            'its Scanpy sc.score_genes() Pathway Score for the Luminal Tumor Core signature.',
            '',
            'LEFT sub-panel : all cells coloured by continuous pathway score (viridis).',
            'RIGHT sub-panel: cells inside SPINDLE top-match tiles highlighted over',
            '                 greyscale background (similar to fig_gene_sig_luminal.png).',
            '',
            'Columns:',
            '  x             -- Spatial x-coordinate of the cell centroid (microns)',
            '  y             -- Spatial y-coordinate of the cell centroid (microns)',
            '  pathway_score -- Scanpy sc.score_genes() value; higher = stronger signature',
            '',
            'Source CSV : results/gene_signature_search/breast_cancer/',
            '             Luminal_Tumor_Core_spatial_cells.csv',
            'Generated by: benchmarks/gene_signature_search.py  (dataset: breast_cancer)',
        ]
        write_csv_with_header(df_cells, OUT_DIR / 'panel_F_spatial_cells.csv', cells_header)
    else:
        print(f'  SKIP Panel F spatial cells -- source not found: {cells_src}')

    # -- Top-match tiles ------------------------------------------------------
    if matches_src.exists():
        df_matches = pd.read_csv(matches_src)
        matches_header = [
            'Panel F -- Luminal Tumour Core: SPINDLE Top-Match Tile Bounding Boxes',
            '',
            'Rectangle patches drawn over the spatial map to highlight tiles returned by',
            'SPINDLE for the Luminal Tumor Core gene-list query. Rank 1 = best match.',
            '',
            'Columns:',
            '  rank    -- Retrieval rank (1 = top match)',
            '  tile_id -- Internal tile index in the spatial index',
            '  x0, y0  -- Bottom-left corner of the tile bounding box (microns)',
            '  x1, y1  -- Top-right corner of the tile bounding box (microns)',
            '',
            'Source CSV : results/gene_signature_search/breast_cancer/',
            '             Luminal_Tumor_Core_top_matches.csv',
            'Generated by: benchmarks/gene_signature_search.py  (dataset: breast_cancer)',
        ]
        write_csv_with_header(df_matches, OUT_DIR / 'panel_F_top_matches.csv', matches_header)
    else:
        print(f'  SKIP Panel F top matches -- source not found: {matches_src}')

    # -- Pathway scores -------------------------------------------------------
    ROW_TO_LABEL = {
        'Luminal_Tumor_Core':      'Invasive Tumour\n& DCIS Core',
        'Basal_Myoepithelial':     'Myoepithelial\n& Basal Layer',
        'Proliferation_Signature': 'Proliferating\nTumour Cells',
        'Endothelial_Vascular':    'Vasculature &\nEndothelial',
        'Macrophage_Myeloid':      'Macrophage &\nDendritic Cell',
    }
    FALLBACK = {
        'Invasive Tumour\n& DCIS Core':  {'background_score': 2.231,  'enrichment_score_at_10': 5.579},
        'Myoepithelial\n& Basal Layer':  {'background_score': -0.017, 'enrichment_score_at_10': 0.994},
        'Proliferating\nTumour Cells':   {'background_score': 0.029,  'enrichment_score_at_10': 0.287},
        'Vasculature &\nEndothelial':    {'background_score': 0.011,  'enrichment_score_at_10': 0.191},
        'Macrophage &\nDendritic Cell':  {'background_score': 0.007,  'enrichment_score_at_10': -0.067},
    }

    rows = []
    if metrics_src.exists():
        try:
            df_m = pd.read_csv(metrics_src, index_col=0)
            for row_key, label in ROW_TO_LABEL.items():
                if row_key in df_m.index:
                    rows.append({
                        'niche_key':              row_key,
                        'niche_label':            label,
                        'background_score':       float(df_m.loc[row_key, 'background_score']),
                        'enrichment_score_at_10': float(df_m.loc[row_key, 'enrichment_score_at_10']),
                    })
            if not rows or max(abs(r['background_score']) for r in rows) < 0.1:
                print('  WARNING Panel F: scores implausible -- using paper fallback')
                rows = []
        except Exception as e:
            print(f'  WARNING Panel F: could not read benchmark_metrics.csv ({e}) -- using fallback')
            rows = []

    if not rows:
        for label, vals in FALLBACK.items():
            key = next((k for k, v in ROW_TO_LABEL.items() if v == label), label)
            rows.append({
                'niche_key':              key,
                'niche_label':            label,
                'background_score':       vals['background_score'],
                'enrichment_score_at_10': vals['enrichment_score_at_10'],
            })

    df_pw = pd.DataFrame(rows)
    scores_header = [
        'Panel F -- Pathway Score Comparison (All Five Gene-List Niches)',
        '',
        'Horizontal grouped bar chart: Tissue Background score vs. SPINDLE Top-10',
        'enrichment score for each of the five gene-signature queries on breast-cancer.',
        'Scores are Scanpy sc.score_genes() values.',
        '',
        'Columns:',
        '  niche_key              -- Internal key matching the benchmark CSV index',
        '  niche_label            -- Multi-line label used on the chart y-axis',
        '  background_score       -- Mean sc.score_genes() over all tissue cells',
        '  enrichment_score_at_10 -- Mean sc.score_genes() inside top-10 SPINDLE tiles',
        '',
        'Source CSV : results/gene_signature_search/benchmark_metrics.csv',
        'Generated by: benchmarks/gene_signature_search.py  (dataset: breast_cancer)',
        '',
        'NOTE: If benchmark_metrics.csv is missing or all |background_score| < 0.1,',
        'paper-reported fallback values are used instead.',
    ]
    write_csv_with_header(df_pw, OUT_DIR / 'panel_F_pathway_scores.csv', scores_header)


# -- Entry point --------------------------------------------------------------
def main():
    print('SPINDLE -- Organising panel data ...')
    print(f'  Output directory: {OUT_DIR.relative_to(PROJECT_ROOT)}\n')

    curate_panel_a()
    curate_panel_b()
    curate_panel_c()
    curate_panel_d()
    curate_panel_e()
    curate_panel_f()

    print(f'\n{"="*60}')
    print('Done.  Panel CSVs are in results/panel_data/')
    print('Run scripts/generate_figure_1.py to regenerate figures.')
    print(f'{"="*60}')


if __name__ == '__main__':
    main()
